---
# tasks file for roles/controller-cinder---
# cinder pre-requisitos (executar no controller)
#
#- name: Executando pre-requisitos para cinder(controller)
#  hosts: controller
#  become: True
- name: Procurando novo hosts compute
  shell: cd /root/ && su -s /bin/bash nova -c "nova-manage cell_v2 discover_hosts"

- name: Criando usuario/role/service/endpoints cinder 
  shell: bash /root/criar_usuarios.sh cinder {{cinder_pass}} volumev3 "Serviço de Storage" http://controller:8776/v3/%\(tenant_id\)s

- name: Criando banco cinder
  shell: bash /root/criar_banco.sh cinder cinder "{{cinder_db_pass}}"

- name: Adicionando dns google ao resolv.conf2
  lineinfile:
    dest: /etc/resolv.conf
    regexp: 'nameserver'
    line: 'nameserver 8.8.8.8'

- name: Instalando pacotes cinder
  apt:
    name: "{{packages}}"
    state: present
  vars:
    packages:
      - cinder-api
      - cinder-scheduler
      - python3-cinderclient

- name: Verificando cinder.conf
  stat: path=/etc/cinder/cinder.conf 
  register: verifique
- name: Fazendo backup cinder.conf
  shell: mv /etc/cinder/cinder.conf /etc/cinder/cinder.conf.BKP
  when: verifique.stat.exists

- name: Criando novo arquivo cinder.conf
  copy:
    dest: /etc/cinder/cinder.conf 
    mode: 0640
    group: cinder
    content: |
      [DEFAULT]
      my_ip = 10.0.0.11
      rootwrap_config = /etc/cinder/rootwrap.conf
      api_paste_confg = /etc/cinder/api-paste.ini
      state_path = /var/lib/cinder
      auth_strategy = keystone
      
      transport_url = rabbit://openstack:{{rabbit_pass}}@controller
      enable_v3_api = True
      
      [database]
      connection = mysql+pymysql://cinder:{{cinder_db_pass}}@controller/cinder
      
      [keystone_authtoken]
      www_authenticate_uri = http://controller:5000
      auth_url = http://controller:5000
      memcached_servers = controller:11211
      auth_type = password
      project_domain_name = default
      user_domain_name = default
      project_name = service
      username = cinder
      password = {{cinder_pass}}
      
      [oslo_concurrency]
      lock_path = $state_path/tmp

- name: Populando banco cinder[controller]
  shell: cd /root/ && su -s /bin/bash cinder -c "cinder-manage db sync"

- name: Reiniciando cinder-scheduler
  service:
    name: cinder-scheduler
    state: restarted
    enabled: yes
