---
# tasks file for roles/neutron

- name: Instalando pacotes neutron[compute]
  apt:                                                                                                                                              
    name: "{{packages}}"
    state: present
  vars:
    packages:
      - neutron-common
      - neutron-plugin-ml2
      - neutron-linuxbridge-agent

- name: Verificando neutron.conf[compute]
  stat: path=/etc/neutron/neutron.conf
  register: verifique
- name: Fazendo backup neutron.conf[compute]
  shell: mv /etc/neutron/neutron.conf /etc/neutron/neutron.conf.BKP
  when: verifique.stat.exists

- name: Criando novo arquivo neutron.conf com conteudo[compute]
  copy:
    dest: /etc/neutron/neutron.conf
    mode: 0640
    group: neutron
    content: |
      [DEFAULT]
      core_plugin = ml2
      service_plugins = router
      auth_strategy = keystone
      state_path = /var/lib/neutron
      allow_overlapping_ips = True
      
      transport_url = rabbit://openstack:{{rabbit_pass}}@controller
      
      [agent]
      root_helper = sudo /usr/bin/neutron-rootwrap /etc/neutron/rootwrap.conf
      
      [keystone_authtoken]
      www_authenticate_uri = http://controller:5000
      auth_url = http://controller:5000
      memcached_servers = controller:11211
      auth_type = password
      project_domain_name = default
      user_domain_name = default
      project_name = service
      username = neutron
      password = {{neutron_pass}}
      
      [oslo_concurrency]
      lock_path = $state_path/lock

- name: Editando arquivo neutron ml2_conf.ini[compute]
  lineinfile:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    insertafter: '\[ml2\]'
    line: "{{item.line}}"
  with_items:
    - {'line': "extension_drivers = port_security"}
    - {'line': "mechanism_drivers = linuxbridge"}
    - {'line': "tenant_network_types = vxlan"}
    - {'line': "type_drivers = flat,vlan,vxlan"}

- name: Editando arquivo neutron linuxbridge_agent.ini[compute]
  lineinfile:
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    insertafter: '\[securitygroup\]'
    line: "{{item.line}}"
  with_items:
    - {'line': "enable_security_group = True"}
    - {'line': "firewall_driver = iptables"}
    - {'line': "enable_ipset = True"}

- name: Adicionando local_ip em linuxbridge_agent.ini[compute]
  lineinfile:
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    regexp: '#local_ip'
    line: 'local_ip = 10.0.0.31'

- name: Criando symbolic link para plugin.ini[compute]
  file:
   src: /etc/neutron/plugins/ml2/ml2_conf.ini
   dest: /etc/neutron/plugin.ini
   state: link

- name: Habilitando serviços neutron e reiniciando nova[compute]
  service:
    name: "{{item}}"
    state: restarted
    enabled: yes
  with_items:
    - nova-compute
    - neutron-linuxbridge-agent

