#!/bin/bash
BANCO=$1
USUARIO=$2
SENHA=$3
mysql <<EOF
CREATE DATABASE $BANCO;
GRANT ALL PRIVILEGES ON $BANCO.* TO '$USUARIO'@'localhost' IDENTIFIED BY '$SENHA';
GRANT ALL PRIVILEGES ON $BANCO.* TO '$USUARIO'@'%' IDENTIFIED BY '$SENHA';
FLUSH PRIVILEGES;
EOF
